import Head from 'next/head'
import Link from 'next/link'

export default function Home () {
  return (
    <>
      <Head>
        <title>Next App Demo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Link href={'/static'}>Static page</Link>
      <br />
      <br />
      <Link href={'/ssr'}>SSR page</Link>
      <br />
      <br />
      <Link href={'/spa'}>SPA page</Link>
      <br />
      <br />
      <Link href={'/spagraphql'}>SPA page graphql</Link>
      <br />
      <br />
      <Link href={'/env'}>Env</Link>
      <br />
      <br />
      <Link href={'/api/brands'}>Json API endpoint</Link>
      <br />
      <br />
      <Link href={'/error'}>Error page</Link>
    </>
  )
}
